version: '3'

services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - dev_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  analytics-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8090"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgresql
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    networks:
      - dev_network
    restart: on-failure

volumes:
  postgres_data:

networks:
  dev_network: